title: Carrie Filion
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
description: Ph.D. Candidate in Physics and Astronomy
seconddescription: Soon to be a Flatiron Research Fellow
logo: new_headshot.jpg
favicon: favicon.ico
