title: Carrie Filion
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
description: Ph.D. Candidate in Physics and Astronomy at the Johns Hopkins University in Baltimore, MD
seconddescription: Future Investigators in NASA Earth and Space Science and Technology (FINESST) fellow
logo: new_headshot.jpg
favicon: favicon.ico
