title: Carrie Filion
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
description: Ph.D. Candidate in Physics and Astronomy
seconddescription: Future Investigators in NASA Earth and Space Science and Technology (FINESST) Grant winner
logo: new_headshot.jpg
favicon: favicon.ico
