title: Carrie Filion
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme
description: Incoming Flatiron Research Fellow, Fall 2024 
seconddescription: Ph.D. in Astronomy and Astrophysics from Johns Hopkins University
logo: new_headshot.jpg
favicon: favicon.ico
